myfirst/apps/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
	path('', views.index, name = 'index'),
	path('create', views.create, name = 'create'),
	path('<int:article_id>/', views.detail, name = 'detail'),
	path('<int:article_id>/leave_comment/', views.leave_comment, name = 'leave_comment')
]

myfirst/apps/main/urls.py
from django.urls import path, include

from . import views

app_name = 'main'
urlpatterns = [
	path('', include('articles.urls')),
	path('about/', views.about, name = 'about'),
	path('contact-us/', views.contacts, name = 'contact-us'),
]

myfirst/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
]

myfirst/apps/about/models.py
from django.db import models

# Create your models here.

myfirst/apps/articles/models.py
import datetime
from django.db import models

from django.utils import timezone

class Article(models.Model):
	article_title = models.CharField('Название статьи', max_length = 200)
	article_text = models.TextField('Текст статьи')
	pub_date = models.DateTimeField('Дата публикации')

	def __str__(self):
		return self.article_title

	def was_published_recently(self):
		return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))

	class Meta:
		verbose_name = 'Статья'
		verbose_name_plural = 'Статьи'

class Comment(models.Model):
	article = models.ForeignKey(Article, on_delete = models.CASCADE)
	author_name = models.CharField('Имя автора', max_length = 50)
	comment_text = models.CharField('Текст комментария', max_length = 200)
	pub_date = models.DateTimeField('Дата публикации')

	def __str__(self):
		return self.author_name

	class Meta:
		verbose_name = 'Комментарий'
		verbose_name_plural = 'Комментарии'

myfirst/apps/main/models.py
from django.db import models

class About(models.Model):
	title = models.CharField('Заголовок', max_length = 200)
	text = models.TextField('Текст обо мне')

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = 'Обо мне'
		verbose_name_plural = 'Обо мне'

class Contact(models.Model):
	number = models.CharField('Номер', max_length = 200)
	text = models.TextField('Описание номера')

	def __str__(self):
		return self.number

	class Meta:
		verbose_name = 'Контакты'
		verbose_name_plural = 'Контакты'

myfirst/apps/articles/forms.py
from .models import Article
from django.forms import ModelForm, TextInput, Textarea

from django.utils import timezone

class ArticleForm(ModelForm):
	class Meta:
		d = timezone.now()
		model = Article
		fields = ["article_title", "article_text", 'pub_date']
		widgets = {
			"article_title": TextInput(attrs={
				'type': 'text',
				'class': 'form-control',
				'placeholder': 'Введите название'
				}),
			"article_text": Textarea(attrs={
				'type': 'text',
				'class': 'form-control',
				'placeholder': 'Введите текст'
				}),
			"pub_date": TextInput(attrs={
				'type': 'hidden',
				'class': 'form-control',
				'value': d.strftime("%Y-%m-%d %H:%M:%S")
				}),
		}

myfirst/apps/about/views.py
from django.shortcuts import render

# Create your views here.

myfirst/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect

from django.urls import reverse
from django.utils import timezone

from .models import Article
from .forms import ArticleForm

import pytz

def index(request):
	latest_articles_list = Article.objects.order_by('-pub_date')[:5]
	return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})

def detail(request, article_id):
	try:
		a = Article.objects.get(id = article_id)
	except:
		raise Http404("Статья не найдена!")

	latest_comments_list = a.comment_set.order_by('-id')[:10]

	local_timezone = pytz.timezone('UTC')

	# for c in latest_comments_list:
	# 	print(c.pub_date)
	# 	c.pub_date = c.pub_date.astimezone(local_timezone)
	# 	print(c.pub_date)

	return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list})

def leave_comment(request, article_id):
	try:
		a = Article.objects.get(id = article_id)
	except:
		raise Http404("Статья не найдена!")

	a.comment_set.create(author_name = request.POST['name'], comment_text = request.POST['text'], pub_date = timezone.now())

	return HttpResponseRedirect(reverse('articles:detail', args = (a.id,)))

def create(request):
	error = ''
	if request.method == 'POST':
		form = ArticleForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/articles')
		else:
			error = 'Форма была неверной'

	form = ArticleForm()
	context = {
		'form': form,
		'error': error
	}
	return render(request, 'articles/create.html', context)

myfirst/apps/main/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render

from django.urls import reverse

from .models import About, Contact

def about(request):
	info = About.objects.get(id = 1)
	return render(request, 'main/about.html', {'info': info})

def contacts(request):
	info = Contact.objects.get(id = 1)
	return render(request, 'main/contacts.html', {'info': info})

myfirst/templates/articles/create.html
{% extends 'base.html' %}

{% block title %}Создать новость{% endblock %}



{% block content %}

	<h1>Создать новость</h1>
	
	<form method="POST">
		{% csrf_token %}

	  <div class="form-group">
	    <label for="exampleInputEmail1">Название статьи</label>
	    {{ form.article_title }}
	    <!-- <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Введите название" name="title"> -->
	  </div>
	  <div class="form-group">
	    <label for="exampleInputPassword1">Текст статьи</label>
	    {{ form.article_text }}
	    <!-- <textarea type="text" class="form-control" id="exampleInputPassword1" placeholder="Введите текст" name="text"></textarea> -->
	  </div>
	  <div>
	  	{{ form.pub_date }}
	  </div>
	  <hr>
	  <button type="submit" class="btn btn-success">Submit</button>
	  <span>{{ error }}</span>
	</form>


{% endblock %}

myfirst/templates/articles/detail.html
{% extends 'base.html' %}
{% load tz %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}

<h2>{{article.article_title}}</h2>

<p>{{article.article_text}}</p>

<em>{{article.pub_date}}</em>

<!-- {% if article.was_published_recently %}
НОВАЯ СТАТЬЯ!
{% endif %} -->

<hr>

<div class="row">

	<div class="col-sm-5 col-md-6 col-12 pb-4">
		<h1>Комментарии</h1>

	{% get_current_timezone as TIME_ZONE %}

	{% if latest_comments_list %}
		{% for c in latest_comments_list %}
			<div class="comment mt-4 text-justify float-left">
				<img src="https://i.imgur.com/CFpa3nK.jpg" alt="" class="rounded-circle" width="40" height="40">
			    <h4>{{c.author_name}}</h4> <span>- {{ c.pub_date }} </span> <br>
			    <p>{{c.comment_text}}</p>
			</div>
		{% endfor %}
	{% else %}
		<h4>Комментарии не найдены! Станьте первым :)</h4>
	{% endif %}

	</div>

	<hr>

	<div class="col-md-5 col-12 mt-4">
	    <form id="algin-form" action="{% url 'articles:leave_comment' article.id %}" method="POST">
	    	{% csrf_token %}
	        <div class="form-group">
	            <h4>Оставить комментарий</h4>
	            <label for="message">Текст</label>
	            <textarea name="text" id="" msg cols="30" rows="5" class="form-control"></textarea>
	        </div>
	        <div class="form-group">
	        	<label for="name">Ваше имя</label>
	        	<input type="text" name="name" id="fullname" class="form-control">
	        	<input type="hidden" name="pub_date" class="form-control">
	        </div>
	        <div class="form-group">
	        	<button type="submit" id="post" class="btn btn-success">Жмяк</button>
	        </div>
	    </form>
	</div>
</div>
{% endblock %}

myfirst/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Последние статьи{% endblock %}


{% block content %}

	{% if latest_articles_list %}

		{% for a in latest_articles_list %}
			<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
		        <div class="col-md-6 px-0">
		          <h1 class="display-4 font-italic">{{a.article_title}}</h1>
		          <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what's most interesting in this post's contents.</p>
		          <p class="lead mb-0"><a href="{% url 'articles:detail' a.id %}" class="text-white font-weight-bold">Читать дальше...</a></p>
		        </div>
			</div>
			<hr>
		{% endfor %}

	{% else %}
		Статьи не найдены )=
	{% endif %}

{% endblock %}

myfirst/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}Мой блог{% endblock %}</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}" />
</head>
<body>

	<div class="container">
		<header>
			
			<ul class="menu-main">

			  <li><a href="{% url 'articles:index' %}">Blog</a></li>
			  <li><a href="{% url 'main:about' %}">About</a></li>
			  <li><a href="{% url 'main:contact-us' %}">Contact</a></li>
			  <li><a href="{% url 'articles:create' %}">Add</a></li>
			</ul>
		</header>
		
		
		{% block content %}{% endblock %}
		
	</div>




	
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	
</body>
</html>

myfirst/templates/main/about.html
{% extends 'base.html' %}

{% block title %}Обо мне{% endblock %}



{% block content %}

	{% if info %}

		<h1>{{info.title}}</h1>
		<p>{{info.text}}</p>

	{% else %}
		Информация не найдена
	{% endif %}

{% endblock %}

myfirst/templates/main/contacts.html
{% extends 'base.html' %}

{% block title %}Контакты{% endblock %}



{% block content %}

	<h1>{{info.number}}</h1>
	<p>{{info.text}}</p>

{% endblock %}